micronaut:
  application:
    name: javapro
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3

liquibase:
  enabled: true
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.xml' # <4>